services:
  - type: web
    name: whatsapp-bot
    runtime: python
    repo: https://github.com/tarasttv/whatsapp_bot
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GOOGLE_CREDENTIALS_JSON
        value: PLACEHOLDER_REPLACE_IN_RENDER_DASHBOARD
      - key: TWILIO_ACCOUNT_SID
        value: PLACEHOLDER
      - key: TWILIO_AUTH_TOKEN
        value: PLACEHOLDER
      - key: TWILIO_PHONE_NUMBER
        value: PLACEHOLDER

